[package]
name = "rust-todo"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.9.0-alpha.1"
tokio = { version = "1", features = ["full"] }
sqlx = { version = "0.7", features = ["runtime-tokio-rustls", "postgres"] }
dotenv = "0.15"
