#!/bin/bash
# https://github.com/adriancooney/Taskfile#install

function run {
  cargo run
}

function up_test_db {
  docker compose up -d
}

function test {
  ./Taskfile up_test_db

  # 並列だとテストデータがコンフリクトして失敗するため、1スレッドに設定
  cargo test -- --test-threads=1 "$@"
}

function start {
  echo "start task not implemented"
}

function default {
  help
}

function help {
    echo "$0 <task> <args>"
    echo "Tasks:"
    compgen -A function | cat -n
}

TIMEFORMAT="Task completed in %3lR"
time ${@:-default}
